spring:
  redis:
    host: 192.168.8.203
    password: taihe123?
    port: 6379
    timeout: 3000
    database: 2
    lettuce:
      pool:
        max-wait: 1000
        max-active: 2000
        max-idle: 10
        min-idle: -1
#  boot:
#     enableautoconfiguration: false


config:
  test:
    value: 测试
